### ISSUE TITLE
Does not work in Kodi Nexus 20.x

### ISSUE THREAD

**Issue by fcr** [XBMCil/service.subtitles.ktuvit#10]
For Kodi Nexus (20.x) running on MacOS 12.6.5 the plugin no longer works. It generates an error both when checking the login and when trying to download a subtitle.
The plugin worked with no problems for Kodi Matrix (19.x)

**Comment by CaTzil** [comment]
Hi, thank you for reporting this issue, I will check what went wrong ASAP

**Comment by CaTzil** [comment]
`V4.0.0` should solve the compatibility issue

**Comment by fcr** [comment]
Thank you and a big thank you for the effort
