### ISSUE TITLE
add 4.0.0 to the releases

### ISSUE THREAD

**Issue by ByteTal** [XBMCil/service.subtitles.ktuvit#11]
It took me 30 minuets to understand that I need to download the source file as a zip to get the 4.0.0 add-on. it will be alot easier if you add it to the releases.

**Comment by CaTzil** [comment]
Done, thanx

**Comment by ByteTal** [comment]
👍

**Comment by TwilightMercy** [comment]
Will you set up Kodi repository for your addons?

**Comment by ByteTal** [comment]
?

**Comment by CaTzil** [comment]
It suppose to by on the original kodi repo, 
It just not approved yet 
https://github.com/xbmc/repo-scripts/pull/2442
