### ISSUE TITLE
dependency not met - beautifulsoup4 ver 4.6.3

### ISSUE THREAD

**Issue by ShlomiD83** [XBMCil/service.subtitles.ktuvit#5]
can't install the latest version, dependency not met error.
please advise.

**Comment by CaTzil** [comment]
Hi, 
I don't know how did you installed it, but on my Kodi (ver 18) it works.

You are probably didn't install it via zip installation, therefore Kodi didn't got a chance to install the deps. (happened on my device as well).
All I did was to go to the addon's dependency management and install BS4 from there.
BTW, this is still under development (currently Ktuvit.me doesn't have a normal API, and a sane way to search movies :| )

**Comment by ShlomiD83** [comment]
Hi CaTz,
I've tried normal zip installation like every other time i install a zip file.
maybe you have a repo installed that has that dependency.
can you try ziping the script.module.beautiful4 folder and uploading it so i can try to install it?

**Comment by ShlomiD83** [comment]
I tried searching online for that specific version (4.6.3) and couldn't find it anywhere, only older version.

**Comment by ShlomiD83** [comment]
BTW version 1.2.0 isn't working anymore, not returning results for movies & tv shows.

**Comment by CaTzil** [comment]
You are correct... weird, it works on my devices...

I will downgrade it to 4.6.2.
I've used it this morning... it works only with TV-shows, as explained there is no "good" way to download movies (yet)

**Comment by ShlomiD83** [comment]
ok, thank you.

**Comment by ShlomiD83** [comment]
maybe you should check out "all subs" code, it searches Ktuvit and returns results for movies also.

**Comment by CaTzil** [comment]
> maybe you should check out "all subs" code, it searches Ktuvit and returns results for movies also.
