### ISSUE TITLE
beautifulsoup4 לא משתף פעולה. Error

### ISSUE THREAD

**Issue by SubEdict** [XBMCil/service.subtitles.ktuvit#6]
beautifulsoup4  לא ניתן להתקין את הזיפ, בעיה עם
Kodi 18.8 Win 10/7 x64.

**Comment by CaTzil** [comment]
Hi,

Can you try to install v2.2.1?

**Comment by SubEdict** [comment]
Wow, you're fast, Ok trying now.

Upadate 2.2.1:
All Good! Works great. 👍
