### ISSUE TITLE
Ktuvit encryption mechanism

### ISSUE THREAD

**Issue by dornizar** [XBMCil/service.subtitles.ktuvit#7]
Hi there!
please check out my implementation of Ktuvit's password hashing & encryption (KtuvitEncryptor class), this includes AES. PBKDF2 hashing, python implementation of JS-Crypto and implementation of primitive JS functions (parseInt, bit-shifting, etc.).
this will solve the annoying password encryption issue:

https://github.com/dornizar/Sub-Zero.bundle/blob/master/Contents/Libraries/Shared/subliminal_patch/providers/ktuvit.py

**Comment by CaTzil** [comment]
Thanx @dornizar, but I will require many libs (which not all of them available for kodi).

I don't think that it worth it, this password thing is onetime thing, which then cached.
