### ISSUE TITLE
Erorrs

### ISSUE THREAD

**Issue by adirt4289** [XBMCil/service.subtitles.ktuvit#8]
הורדתי תגירסא האחרונה על הקודי החדש 19 ויש לי שגיאה בחיפוש

**Comment by CaTzil** [comment]
Bring your comp here, I will fix it 😅

Jokes a side, please add some logs that shows what happened on your comp.

**Comment by adirt4289** [comment]
> Bring your comp here, I will fix it 😅
> 
> Jokes a side, please add some logs that shows what happened on your comp.

Dude I have a version lowered and I still have an error, while searching for a subtitle I get an error:

https://pastebin.com/AD0eX5SB

**Comment by CaTzil** [comment]
Can you attach a [debug log](https://kodi.wiki/index.php?title=Log_file)?

**Comment by adirt4289** [comment]
> Can you attach a [debug log](https://kodi.wiki/index.php?title=Log_file)?

https://pastebin.com/AD0eX5SB

**Comment by CaTzil** [comment]
> > Can you attach a [debug log](https://kodi.wiki/index.php?title=Log_file)?
> 
> https://pastebin.com/AD0eX5SB

This is not a **DEBUG** log...
Turn on the debug mode in kodi's settings (or using <kbd>Ctrl+Shift+d</kbd>), and then try to download a subtitle.

**Comment by adirt4289** [comment]
> > > Can you attach a [debug log](https://kodi.wiki/index.php?title=Log_file)?
> > 
> > 
> > https://pastebin.com/AD0eX5SB
> 
> This is not a **DEBUG** log...
> Turn on the debug mode in kodi's settings (or using Ctrl+Shift+d), and then try to download a subtitle.

![image](https://user-images.githubusercontent.com/53193593/108682215-b5753180-74f8-11eb-9205-4ba6846b99d7.png)

https://paste.kodi.tv/oxiweyesig.kodi

**Comment by CaTzil** [comment]
Your Ktuvit plugin is 2.2.1 which doesn't supports Kodi 19...
https://github.com/XBMCil/service.subtitles.ktuvit/blob/master/changelog.txt

Try to install v3.0.0 :]

https://github.com/XBMCil/service.subtitles.ktuvit/releases

**Comment by adirt4289** [comment]
> Your Ktuvit plugin is 2.2.1 which doesn't supports Kodi 19...
> https://github.com/XBMCil/service.subtitles.ktuvit/blob/master/changelog.txt
> 
> Try to install v3.0.0 :]
> 
> https://github.com/XBMCil/service.subtitles.ktuvit/releases

אחי כתבתי לך ששינמכתי גירסא לקודי 18.9

**Comment by CaTzil** [comment]
Sorry, missed it.

Ok, so the issue is that you didn't configured `hebrew` as a valid subtitle lang, therefore it "explodes".
Go to Kodi settings -> Player settings -> Language

![image](https://user-images.githubusercontent.com/3762838/108685020-4d284f00-74fc-11eb-988d-2e332c3f2213.png)

**Comment by adirt4289** [comment]
> Sorry, missed it.
> 
> Ok, so the issue is that you didn't configured `hebrew` as a valid subtitle lang, therefore it "explodes".
> Go to Kodi settings -> Player settings -> Language
> 
> ![image](https://user-images.githubusercontent.com/3762838/108685020-4d284f00-74fc-11eb-988d-2e332c3f2213.png)

worked! tnx

**Comment by adirt4289** [comment]
![image](https://user-images.githubusercontent.com/53193593/108686083-9b8a1d80-74fd-11eb-9bec-1906bf9e3f16.png)

what about this error?

**Comment by CaTzil** [comment]
Debug Logs? :]

**Comment by adirt4289** [comment]
> Debug Logs? :]

https://paste.kodi.tv/lofeqotucu.kodi

in manual search it finds the subtitle

**Comment by CaTzil** [comment]
There is no error in to logs that comes from `ktuvit.me` addon

**Comment by adirt4289** [comment]
> There is no error in to logs that comes from `ktuvit.me` addon

so what should i do?

in manual it works fine!

**Comment by CaTzil** [comment]
Add a log that will contain the error, without it I can't help 🤷🏽‍♂️

**Comment by adirt4289** [comment]
> Add a log that will contain the error, without it I can't help 🤷🏽‍♂️

https://paste.kodi.tv/ukociwobol.kodi

(maybe it because i have alreadylocal subtitle at the movie's folder?)


![image](https://user-images.githubusercontent.com/53193593/108687549-87472000-74ff-11eb-8372-c25d7db110d5.png)

**Comment by adirt4289** [comment]
> Add a log that will contain the error, without it I can't help 🤷🏽‍♂️

https://paste.kodi.tv/ukociwobol.kodi

**Comment by CaTzil** [comment]
No error from Ktuvit (and no subtitle found)...
![image](https://user-images.githubusercontent.com/3762838/108689113-5c5dcb80-7501-11eb-912f-d1788fe938c7.png)

**Comment by adirt4289** [comment]
> No error from Ktuvit (and no subtitle found)...
> ![image](https://user-images.githubusercontent.com/3762838/108689113-5c5dcb80-7501-11eb-912f-d1788fe938c7.png)

its only in this movie!. strange....

and like i said in manual it finds!!!!

can i talk with you in discord or something? even in other add ons this movie refusing to find subtitles!

edit: now i see there are more few movies that cant find subtitles only in manual mode!

**Comment by CaTzil** [comment]
The plugin may not find subtitles, sometimes the movie name is not exactly as it is in the website... therefore there is a manual search that you can enter what ever you want :]

**Comment by adirt4289** [comment]
> The plugin may not find subtitles, sometimes the movie name is not exactly as it is in the website... therefore there is a manual search that you can enter what ever you want :]

ok great! now i know at least, good day gever XD
